description: This file stores settings for Dart & Flutter DevTools.
documentation: https://docs.flutter.dev/tools/devtools/extensions#configure-extension-enablement-states
extensions:


analyzer:
  exclude:
    - '**/*.g.dart'
  errors:
    invalid_annotation_target: ignore